#!/usr/bin/env bash
# shellcheck enable=require-variable-braces
# shellcheck disable=SC2034

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/../src/version)"

    if [ -f "${ver}" ]; then
        cat "${ver}"
        return
    fi

    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="RetroPie-Setup"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG
